---
title: "Seurat SCTransform integration workflow"
author: "Florian Deckert"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include = FALSE}

# Set knitr chunk 
knitr::opts_chunk$set(
  
	echo      = FALSE,
	message   = FALSE,
	warning   = FALSE,
	cache     = FALSE,
	out.width = "100%",
	progress  = FALSE,
	results   = "hide"
	
	)

# Set knitr global 

knitr::opts_knit$set(root.dir = gsub("/script/seurat", "", getwd()))


```

```{r allocate memory}

memory.limit(size = 4 * 32676)

```

```{r load libraries}

library(Seurat)

library(dplyr)

library(ggplot2)
library(RColorBrewer)
library(patchwork)

```

```{r load source files}

# Plotting Theme
source("plotting_global.R")

```

```{r global parameter}

# Parameter 

# Plotting Theme
theme_set(theme_global_set()) # From project global source()

```

```{r files}

so_file <- "data/seurat_object/so_qc.rds"

```

# Parameter settings

### File names 
Import Seurat object: **`r so_file`**  

```{r import seurat objects}

so <- readRDS(so_file)

```

# Sample split 

```{r}

so <- SplitObject(so, split.by = "sample_name")

```

# SCTransform 

```{r}

variable_features_n <- 3000
vars_to_regress <- c("pMt_RNA")
so <- lapply(so, SCTransform, variable.features.n = variable_features_n, vars.to.regress = vars_to_regress)

```

# Integration 

```{r}

anchor_features <- SelectIntegrationFeatures(so, nfeatures = 3000)
so <- PrepSCTIntegration(so, anchor.features = anchor_features)
anchorset <- FindIntegrationAnchors(so, normalization.method = "SCT", anchor.features = anchor_features)
so_int_sct <- IntegrateData(anchorset = anchorset, normalization.method = "SCT", new.assay.name = "INT")

```

# Save output 

```{r}

integration <- list(
  
  anchor_features = anchor_features, 
  anchorset = anchorset, 
  so_int_sct = so_int_sct
  
)

saveRDS(integration, "integration.rds")

```

# Session info

```{r session info, results="markup"}

sessionInfo()

```